### PR TITLE
go.mod: update dependencies (take 2)

### LINKED ISSUE #203: go.mod: update dependencies / CI failing
Accidentally pushed [`cmd/continuity: remove FUSE for macOS`](https://github.com/containerd/continuity/commit/5df4731d45253217b8fe4ebf823fffda8da5a7ae) and [`go.mod: update dependencies`](https://github.com/containerd/continuity/commit/e3648687add4203d03811191b4e5692f516d355b`) to the `main` branch directly without opening a PR 😞 , sorry 

And CI is failing: https://github.com/containerd/continuity/runs/5847057049?check_suite_focus=true

```
Vendor directory
  go: downloading golang.org/x/sys v0.0.0-20220405210540-1e041c57c461
  go: downloading github.com/golang/protobuf v1.5.2
  go: downloading github.com/opencontainers/go-digest v1.0.0
  go: downloading github.com/Microsoft/go-winio v0.5.2
  go: downloading github.com/sirupsen/logrus v1.8.1
  go: downloading golang.org/x/sync v0.0.0-20210220032[95](https://github.com/containerd/continuity/runs/5847057049?check_suite_focus=true#step:4:95)1-036812b2e83c
  go: downloading google.golang.org/protobuf v1.26.0
  go: downloading github.com/google/go-cmp v0.5.5
  go: downloading github.com/stretchr/testify v1.3.0
  go: downloading github.com/davecgh/go-spew v1.1.1
  go: downloading github.com/pmezard/go-difflib v1.0.0
  go: downloading golang.org/x/xerrors v0.0.0-2019[120](https://github.com/containerd/continuity/runs/5847057049?check_suite_focus=true#step:4:120)4190536-9bdfabe68543
  
  These files were modified:
  
   M go.mod
   M go.sum
   M vendor/modules.txt
  ?? vendor/github.com/Microsoft/go-winio/pkg/guid/guid_nonwindows.go
  ?? vendor/github.com/Microsoft/go-winio/pkg/guid/guid_windows.go
  ?? vendor/github.com/golang/protobuf/proto/buffer.go
  ?? vendor/github.com/golang/protobuf/proto/defaults.go
  ?? vendor/github.com/golang/protobuf/proto/proto.go
  ?? vendor/github.com/golang/protobuf/proto/registry.go
  ?? vendor/github.com/golang/protobuf/proto/text_decode.go
  ?? vendor/github.com/golang/protobuf/proto/text_encode.go
  ?? vendor/github.com/golang/protobuf/proto/wire.go
  ?? vendor/github.com/golang/protobuf/proto/wrappers.go
  ?? vendor/golang.org/x/sys/unix/asm_bsd_386.s
  ?? vendor/golang.org/x/sys/unix/asm_bsd_amd64.s
  ?? vendor/golang.org/x/sys/unix/asm_bsd_arm.s
  ?? vendor/golang.org/x/sys/unix/asm_bsd_arm64.s
  ?? vendor/golang.org/x/sys/unix/asm_zos_s390x.s
  ?? vendor/golang.org/x/sys/unix/dev_zos.go
  ?? vendor/golang.org/x/sys/unix/epoll_zos.go
  ?? vendor/golang.org/x/sys/unix/fstatfs_zos.go
  ?? vendor/golang.org/x/sys/unix/ifreq_linux.go
  ?? vendor/golang.org/x/sys/unix/ioctl_linux.go
  ?? vendor/golang.org/x/sys/unix/ioctl_zos.go
  ?? vendor/golang.org/x/sys/unix/syscall_linux_alarm.go
  ?? vendor/golang.org/x/sys/unix/syscall_linux_ppc.go
  ?? vendor/golang.org/x/sys/unix/syscall_zos_s390x.go
  ?? vendor/golang.org/x/sys/unix/sysvshm_linux.go
  ?? vendor/golang.org/x/sys/unix/sysvshm_unix.go
  ?? vendor/golang.org/x/sys/unix/sysvshm_unix_other.go
  ?? vendor/golang.org/x/sys/unix/zerrors_linux_ppc.go
  ?? vendor/golang.org/x/sys/unix/zerrors_zos_s390x.go
  ?? vendor/golang.org/x/sys/unix/zsyscall_linux_ppc.go
  ?? vendor/golang.org/x/sys/unix/zsyscall_zos_s390x.go
  ?? vendor/golang.org/x/sys/unix/zsysnum_linux_ppc.go
  ?? vendor/golang.org/x/sys/unix/zsysnum_zos_s390x.go
  ?? vendor/golang.org/x/sys/unix/ztypes_illumos_amd64.go
  ?? vendor/golang.org/x/sys/unix/ztypes_linux_ppc.go
  ?? vendor/golang.org/x/sys/unix/ztypes_zos_s390x.go
  ?? vendor/golang.org/x/sys/windows/setupapi_windows.go
  ?? vendor/golang.org/x/sys/windows/types_windows_arm64.go
  ?? vendor/google.golang.org/
  
  Error: Process completed with exit code 1.
```

### PR DESCRIPTION
**Pull request by AkihiroSuda**
Fix #203

### CODE REVIEW

**Comment by AkihiroSuda** [comment]
Let me release v0.3.0 after merging this

**Review by estesp — APPROVED** [review]
LGTM

**Review by fuweid — APPROVED** [review]

**Comment by fuweid** [comment]
@AkihiroSuda didn't see 0.3.0 tag. Is it ok to merge?

**Comment by AkihiroSuda** [comment]
> @AkihiroSuda didn't see 0.3.0 tag. Is it ok to merge?

The tag will be created after merging.

**Comment by AkihiroSuda** [comment]
Tagged: https://github.com/containerd/continuity/releases/tag/v0.3.0

**Pull request merged**
