### PR TITLE
Add xattr definitions for power/s390x

### PR DESCRIPTION
**Pull request by tonistiigi**
@estesp 

Signed-off-by: Tonis Tiigi <tonistiigi@gmail.com>

### CODE REVIEW

**Comment by stevvooe** [comment]
LGTM

@dmcgowan PTAL

**Comment by estesp** [comment]
ping @tophj-ibm ; do you want do a quick look at this? Looks correct to me and is generated from the Go implementations, so I assume correct.

**Comment by tophj-ibm** [comment]
Thanks @estesp and @tonistiigi !!

I just want to reiterate #63 in that the syscall in general isn't the greatest for a lot of reasons and should be switched to /x/sys ASAP. This is especially true for non-x86 architectures where a lot of calls haven't been well tested, and if an issue arrises it often takes an entire release cycle to get in. /rant 😄 

Having said that, I don't know of any issues with xattr, and I did check all of these calls against /x/sys just in case and I these look fine to me.

**Comment by dmcgowan** [comment]
LGTM

**Comment by justincormack** [comment]
@tophj-ibm the only constants here are the actual syscall numbers which are less likely to be wrong. But we could consider other ways of doing this.

**Pull request merged**
