### PR TITLE
move cmd/continuity to its own go module

### PR DESCRIPTION
**Pull request by thaJeztah**
this command-line is mostly used for testing and debugging, and its
dependencies should not be a dependency of the main module (library)

- addresses https://github.com/containerd/continuity/issues/199
- addresses / supersedes https://github.com/containerd/continuity/pull/194
    - for the main module, that is, but we can decide to update the cobra version in the cmd/package in a follow-up

### CODE REVIEW

**Comment by thaJeztah** [comment]
after this, we should consider removing the `vendor` directory as the main module is then a library

**Comment by thaJeztah** [comment]
need to tweak some make targets;

```
+ /home/runner/work/continuity/continuity/src/github.com/containerd/continuity/bin/continuity
main module (github.com/containerd/continuity) does not contain package github.com/containerd/continuity/cmd/continuity
make: *** [/home/runner/work/continuity/continuity/src/github.com/containerd/continuity/bin/continuity] Error 1
Error: Makefile:49: recipe for target '/home/runner/work/continuity/continuity/src/github.com/containerd/continuity/bin/contin
```

**Review by AkihiroSuda — APPROVED** [review]

**Comment by thaJeztah** [comment]
I'll do a rebase (https://github.com/containerd/continuity/pull/198 was merged)

**Comment by thaJeztah** [comment]
rebased 👍 @kzys @dmcgowan PTAL if this LGTY

**Review by kzys — APPROVED** [review]

**Pull request merged**
