### PR TITLE
sysx: remove custom implementation of CopyFileRange

### PR DESCRIPTION
**Pull request by tklauser**
golang.org/x/sys/unix provides the CopyFileRange syscall function on
Linux already, so there is no need for a custom wrapper. Now that
containerd switched to use the version from x/sys/unix (via
containerd/containerd#1312), there seem to be no remaining users of
sysx.CopyFileRange (according to [1]) and it can safely be removed.

  [1] https://godoc.org/github.com/containerd/continuity/sysx?importers

This should help #63 moving forward.

Signed-off-by: Tobias Klauser <tklauser@distanz.ch>

### CODE REVIEW

**Comment by tklauser** [comment]
Pushed an update to mention #63 in the commit message, since it should also help with that.

**Comment by AkihiroSuda** [comment]
SGTM

@stevvooe @dmcgowan PTAL?

**Comment by dmcgowan** [comment]
LGTM

**Comment by dmcgowan** [comment]
@AkihiroSuda I will take your SGTM as an LGTM 😄

**Pull request merged**
