### PR TITLE
go.mod: github.com/golang/protobuf v1.3.5

### PR DESCRIPTION
**Pull request by thaJeztah**
Follow-up to https://github.com/containerd/continuity/pull/157; only the last commit (https://github.com/containerd/continuity/commit/92bffbb5487c5adce7fddddfb210f3f4c3cad6d0) is new. This version matches what's used in containerd and buildkit, and Cobra 1.0 depends on protobuf > v1.3.1

Keeping this separate, as it may have to be reviewed separately

### CODE REVIEW

**Comment by thaJeztah** [comment]
this one should also be ready for review @estesp @dmcgowan (sorry for the multiple PR's, trying to somewhat keep changes reviewable)

**Review by estesp — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
@AkihiroSuda @dmcgowan ptal

**Comment by thaJeztah** [comment]
@AkihiroSuda @dmcgowan ptal

**Review by AkihiroSuda — APPROVED** [review]

**Pull request merged**
