### PR TITLE
Fix TestDiffDirChangeWithOverlayfs failed

### PR DESCRIPTION
**Pull request by yylt**
Fix TestDiffDirChangeWithOverlayfs failed

### CODE REVIEW

**Comment by yylt** [comment]
@fuweid  PTAL, thanks

**Comment by yylt** [comment]
It's strange that it didn't happen. Let me observe for a while and take another look.

**Comment by fuweid** [comment]
Hi @yylt I close it and please feel free to reopen it if there is bug.

**Pull request closed without merging**
