### PR TITLE
Patch CVE jwt fulnerability

### PR DESCRIPTION
**Pull request by iorvd**
Preface:
There's a known vulnerability in `github.com/dgrijalva/jwt-go` - https://github.com/advisories/GHSA-w73w-5m7g-f7qc

This PR bumps `github.com/spf13/cobra` to `v1.3.0` in order to remove the deprecated and vulnerable library from the list of dependencies.

### CODE REVIEW

**Comment by estesp** [comment]
Thanks for this contribution; can you sign your commit and force push this branch to update the PR? Thanks!

**Comment by iorvd** [comment]
Thanks @estesp!

Linter suggests to replace the deprecated library with a new one:

```
SA1019: Package github.com/golang/protobuf/proto is deprecated:
Use the "google.golang.org/protobuf/proto" package instead.  (staticcheck)
```

However I'm not sure what to do about this so far as these packages have no common `v1.5.2` version.

**Comment by chandumlg** [comment]
Any update on this PR?

**Comment by AkihiroSuda** [comment]
> There's a known vulnerability in `github.com/dgrijalva/jwt-go` - [GHSA-w73w-5m7g-f7qc](https://github.com/advisories/GHSA-w73w-5m7g-f7qc)

This package is not actually consumed in the continuity repo: https://github.com/containerd/continuity/tree/main/vendor/github.com

So, we are not prioritizing this PR, but we are happy to merge this when it gets signed off.

**Comment by estesp** [comment]
cobra has been removed from the library dependencies by the refactoring out of the debug/admin command line tool in #200; I think this can be closed now.

**Pull request closed without merging**
