### PR TITLE
vendor dependencies with vndr (https://github.com/LK4D4/vndr)

### PR DESCRIPTION
**Pull request by ijc**
Ran `vndr init`, sorted the resulting `vendor.conf` and committed the result.
    
Signed-off-by: Ian Campbell <ijc@docker.com>

In my first cut something regenerated `AUTHORS` for me, in my second go around that didn't happen so I forced it with `rm AUTHORS && make AUTHORS`.

### CODE REVIEW

**Comment by estesp** [comment]
Looks like the travis config needs some love to not try and `vet` vendored deps

**Comment by ijc** [comment]
Actually, I think all of `vet`, `build` and `test` in the `Makefile` could do with that. I'll look at it.

**Comment by ijc** [comment]
Seems like the go version could be bumped too it's currently 1.7, 1.8 and tip, I proposed to add 1.9 and drop 1.7.

**Comment by AkihiroSuda** [comment]
ping @stevvooe ptal

**Comment by stevvooe** [comment]
LGTM

**Pull request merged**
